[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "lantern"
version = "0.1.0"
description = "lantern CLI tool"
dependencies = [
    "zeroconf",
    "prompt_toolkit",
    "asyncio"
]


[project.scripts]
lantern = "lantern.cli:main"

